name: Deploy Dataproc Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Upload script to GCS
      run: |
        gsutil cp src/flights_preprocess.py gs://flight-dev/DE/

    # - name: Submit Dataproc job
    #   run: |
    #     gcloud dataproc jobs submit pyspark \
    #       --cluster=your-cluster-name \
    #       --region=your-region \
    #       gs://your-bucket/your-path/your_notebook.py
